AWSTemplateFormatVersion: 2010-09-09
Description: Sample template for launching Falcon Sensor for Linux container image as an ECS Daemon Service to a cluster
Parameters:
  ECSClusterName:
    Type: String
    Description: Cluster name to deploy Falcon Sensor for Linux as a Daemon Service
  CID:
    Type: String
    Description: CrowdStrike Customer ID (CID) value
  FalconImagePath:
    Type: String
    Description: The ECR image path including tag value for the Falcon Sensor for Linux container image
  SensorMemoryReservation:
    Type: String
    Description: Memory Reservation for the Falcon Sensor
    Default: 512
    AllowedValues:
      - 512
      - 1024
      - 2048
      - 3072
      - 4096
      - 5120
      - 6144
      - 7168
      - 8192
      - 9216
      - 10240
      - 11264
      - 12288
      - 13312
      - 14336
      - 15360
      - 16384
      - 17408
      - 18432
      - 19456
      - 20480
      - 21504
      - 22528
      - 23552
      - 24576
      - 25600
      - 26624
      - 27648
      - 28672
      - 29696
      - 30720

  APD:
    Type: String
    Default: ""
    Description: App Proxy Disable (APD)
  APH:
    Type: String
    Default: ""
    Description: App Proxy Host (APH)
  APP:
    Type: String
    Default: ""
    Description: App Proxy Port (APP)
  TRACE:
    Type: String
    Description: Set Trace Level
    Default: none
    AllowedValues:
      - none
      - err
      - warn
      - info
      - debug
  FEATURE:
    Type: String
    Default: ""
    Description: Sensor Feature Options
  TAGS:
    Type: String
    Default: "ecs-ec2-daemon"
    Description: Comma separated list of tags for sensor grouping
  PROVISIONINGTOKEN:
    Type: String
    Default: ""
    Description: Provisioning token value
  BACKEND:
    Type: String
    Default: bpf
    Description: Backend option, allowed values "kernel" and "bpf"
    AllowedValues:
      - bpf
      - kernel

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Mandatory Fields
        Parameters:
          - ECSClusterName
          - CID
          - FalconImagePath
          - SensorMemoryReservation
      - Label:
          default: Optional falconctl install options
        Parameters:
          - TAGS
          - PROVISIONINGTOKEN
          - TRACE
          - APD
          - APH
          - APP
          - FEATURE
          - BACKEND
  
Resources:
  FalconECSTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
        - Name: init-falconstore
          MemoryReservation: 128
          Image: !Ref FalconImagePath
          EntryPoint:
            - "/bin/bash"
          Command:
            - '-c' 
            - 'echo "Running /opt/CrowdStrike/falcon-daemonset-init -i"; /opt/CrowdStrike/falcon-daemonset-init -i'
          Essential: false
          Privileged: true
          ReadonlyRootFilesystem: false
          User: 0
          # LogConfiguration:
          #   LogDriver: awslogs
          #   Options:
          #     awslogs-group: !Sub "/aws/ecs/${ECSClusterName}/crowdstrike/falcon-daemon-service"
          #     awslogs-region: !Ref AWS::Region
          #     awslogs-stream-prefix: "node-init"
        - Name: crowdstrike-falcon-node-sensor
          Image: !Ref FalconImagePath
          Essential: true
          DependsOn:
            - ContainerName: init-falconstore
              Condition: COMPLETE
          Environment:
            - Name: FALCONCTL_OPT_CID
              Value: !Ref CID
            - Name: FALCONCTL_OPT_APD
              Value: !Ref APD
            - Name: FALCONCTL_OPT_APH
              Value: !Ref APH
            - Name: FALCONCTL_OPT_APP
              Value: !Ref APP
            - Name: FALCONCTL_OPT_TRACE
              Value: !Ref TRACE
            - Name: FALCONCTL_OPT_TAGS
              Value: !Ref TAGS
            - Name: FALCONCTL_OPT_FEATURE
              Value: !Ref FEATURE
            - Name: FALCONCTL_OPT_PROVISIONING_TOKEN
              Value: !Ref PROVISIONINGTOKEN
            - Name: FALCONCTL_OPT_BACKEND
              Value: !Ref BACKEND
          MemoryReservation: !Ref SensorMemoryReservation
          MountPoints:
            - ContainerPath: /opt/CrowdStrike/falconstore
              SourceVolume: falconstore
          Privileged: true
          ReadonlyRootFilesystem: false
          User: 0
          # LogConfiguration:
          #   LogDriver: awslogs
          #   Options:
          #     awslogs-group: !Sub "/aws/ecs/${ECSClusterName}/crowdstrike/falcon-daemon-service"
          #     awslogs-region: !Ref AWS::Region
          #     awslogs-stream-prefix: "node-sensor"
      Volumes:
        - Name: falconstore
          Host:
            SourcePath: /opt/CrowdStrike/falconstore
      NetworkMode: host
      IpcMode: host
      PidMode: host
      RuntimePlatform:
        OperatingSystemFamily: LINUX
      RequiresCompatibilities:
        - EC2

  FalconECSService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref ECSClusterName
      SchedulingStrategy: DAEMON
      LaunchType: EC2
      ServiceName: crowdstrike-falcon-node-daemon
      TaskDefinition: !Ref FalconECSTaskDefinition

  # LogGroup:
  #   Type: AWS::Logs::LogGroup
  #   Properties:
  #     LogGroupName: !Sub "/aws/ecs/${ECSClusterName}/crowdstrike/falcon-daemon-service"
